### ISSUE TITLE
Support pandas 2.0

### ISSUE THREAD

**Issue by jtilly** [data-engineering-collective/plateau#92]
Our CI jobs for pandas 2.0 are currently failing (see, e.g., [here](https://github.com/data-engineering-collective/plateau/actions/runs/5052163086/jobs/9064749852#step:11:2011)).

I see (at least) two issues with supporting pandas 2.0:

- https://github.com/pandas-dev/pandas/issues/50127 (open PR [here](https://github.com/pandas-dev/pandas/issues/50127)): this issue is causing our CI failures
- https://github.com/pandas-dev/pandas/pull/52212 changed how pandas is inferring dtypes from scalars, which results in issues when we partition by a datetime (loading the data eagerly will return a `datetime64[ns]`, loading the data as dask data frame will return a `datetime64[s]`). I don't think we have tests for this by the way. That we could address by explicitly setting the units to nanoseconds [here](https://github.com/data-engineering-collective/plateau/blob/d4c4522f5a829d43e3368fc82e1568c91fa352f3/plateau/io_components/metapartition.py#L774).

**Comment by xhochy** [comment]
> @DamianBarabonkovQC @xhochy 

Open for PRs.
